Add "NOUS Ouvert Utile et Simple"
climanifeste/emploi pull request #34
Opened 2019-10-01 08:16 UTC by bastienho

2019-10-01 09:21 UTC, supertanuki commented on README.md
> +* [Developpeur⋅se Web Alternance H/F](https://avecnous.eu/utile/faire/)
Pourquoi ne pas mettre le lien direct https://avecnous.eu/blog/developpeur%c2%b7se-web-alternance-toulouse-2019/ ?

2019-10-01 14:39 UTC, ghost requested changes
Effectivement il vaut mieux mettre le lien vers l'annonce. Cela permet aussi de valider que la PR est légitime.

2019-10-12 09:27 UTC, jffourmond commented
Moi ça me va comme ça.

2019-10-12 09:27 UTC, jffourmond approved these changes

2019-10-16 16:51 UTC, supertanuki approved these changes

2019-10-17 11:08 UTC, merged